// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const AGNES_MODELS = {
	"agnes-2.0-flash": {
		id: "agnes-2.0-flash",
		name: "Agnes 2.0 Flash",
		api: "openai-completions",
		provider: "agnes",
		baseUrl: "https://apihub.agnes-ai.com/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","supportsLongCacheRetention":false},
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 0.03,
			output: 0.15,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 524288,
		maxTokens: 65536,
	} satisfies Model<"openai-completions">,
} as const;
