// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const STEPFUN_MODELS = {
	"step-3.5-flash": {
		id: "step-3.5-flash",
		name: "Step 3.5 Flash",
		api: "openai-completions",
		provider: "stepfun",
		baseUrl: "https://api.stepfun.com/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":false,"maxTokensField":"max_tokens","requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsLongCacheRetention":false,"supportsStrictMode":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.29,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
	"step-3.5-flash-2603": {
		id: "step-3.5-flash-2603",
		name: "Step 3.5 Flash 2603",
		api: "openai-completions",
		provider: "stepfun",
		baseUrl: "https://api.stepfun.com/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":true,"maxTokensField":"max_tokens","requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsLongCacheRetention":false,"supportsStrictMode":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.1,
			output: 0.29,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
	"step-3.7-flash": {
		id: "step-3.7-flash",
		name: "Step 3.7 Flash",
		api: "openai-completions",
		provider: "stepfun",
		baseUrl: "https://api.stepfun.com/v1",
		compat: {"supportsStore":false,"supportsDeveloperRole":false,"supportsReasoningEffort":true,"maxTokensField":"max_tokens","requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsLongCacheRetention":false,"supportsStrictMode":false},
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.19,
			output: 1.13,
			cacheRead: 0.04,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
} as const;
