// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const STEPFUN_STEP_PLAN_MODELS = {
	"step-3.5-flash": {
		id: "step-3.5-flash",
		name: "Step 3.5 Flash",
		api: "openai-completions",
		provider: "stepfun-step-plan",
		baseUrl: "https://api.stepfun.com/step_plan/v1",
		compat: {"requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsReasoningEffort":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.7,
			output: 2.1,
			cacheRead: 0.14,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
	"step-3.5-flash-2603": {
		id: "step-3.5-flash-2603",
		name: "Step 3.5 Flash 2603",
		api: "openai-completions",
		provider: "stepfun-step-plan",
		baseUrl: "https://api.stepfun.com/step_plan/v1",
		compat: {"requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsReasoningEffort":true},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.7,
			output: 2.1,
			cacheRead: 0.14,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
	"step-3.7-flash": {
		id: "step-3.7-flash",
		name: "Step 3.7 Flash",
		api: "openai-completions",
		provider: "stepfun-step-plan",
		baseUrl: "https://api.stepfun.com/step_plan/v1",
		compat: {"requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsReasoningEffort":true},
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.35,
			output: 8.1,
			cacheRead: 0.27,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 250000,
	} satisfies Model<"openai-completions">,
	"step-router-v1": {
		id: "step-router-v1",
		name: "Step Router V1",
		api: "openai-completions",
		provider: "stepfun-step-plan",
		baseUrl: "https://api.stepfun.com/step_plan/v1",
		compat: {"requiresReasoningContentOnAssistantMessages":true,"thinkingFormat":"deepseek","supportsReasoningEffort":false},
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 393216,
	} satisfies Model<"openai-completions">,
} as const;
